healthclinic_system/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("", views.index, name="index"),
    path("users/", include("users.urls", namespace="users"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tester/todo_list_1/todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls'))
]

tester/todo_list_10_user_profile/users/urls.py
from django.urls import path
from .views import MyLoginView, RegisterView, MyProfile #, profile



from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('login/', MyLoginView.as_view(redirect_authenticated_user=True),name='login'),
    path('logout/', LogoutView.as_view(next_page='login'),name='logout'),
    path('register/', RegisterView.as_view(),name='register'),
    path('password-reset/', 
        PasswordResetView.as_view(
            template_name='users/password_reset.html',
            html_email_template_name='users/password_reset_email.html'
        ),
        name='password-reset'
    ),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    
    path('profile/', MyProfile.as_view(), name='profile'),
]

users/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = "users"

urlpatterns = [
  path("admin/", admin.site.urls),

  path("register/admin", views.admin_registration, name="admin_registration"),
  path("register/student", views.student_registration, name="student_registration"),

  path("bsu-alangilan/login", views.user_login, name="user_login"),
  path("bsu-alangilan/logout", views.user_logout, name="user_logout"),

  path("user-admin/dashboard", views.admin_dashboard, name="admin_dashboard"),
  path("user-admin/inventory", views.admin_inventory, name="admin_inventory"),
  path("user-admin/profile", views.admin_profile, name="admin_profile"),
  path("user-admin/student_app", views.admin_student_app, name="admin_student_app"),
  path("user-admin/student_history_profile", views.admin_student_history_profile, name="admin_student_history_profile"),
  path("user-admin/student_history", views.admin_student_history, name="admin_student_history"),
  path("user-admin/student_record_profile", views.admin_student_record_profile, name="admin_student_record_profile"),
  path("user-admin/student_records", views.admin_student_records, name="admin_student_records"),

  path("user-student/home", views.student_home, name="student_home"),
  path("user-student/appointment1", views.student_appointment1, name="student_appointment1"),
  path("user-student/appointment1/<int:appointment_id>", views.student_appointment1, name="student_appointment1_with_id"),
  path("user-student/appointment2/<int:appointment_id>", views.student_appointment2, name="student_appointment2"),
  path("user-student/appointment3/<int:appointment_id>", views.student_appointment3, name="student_appointment3"),
  path("user-student/appointment4_form2/<int:appointment_id>", views.student_appointment4_form2, name="student_appointment4_form2"),
  path("user-student/appointment5/<int:appointment_id>", views.student_appointment5, name="student_appointment5"),
  path("user-student/profile", views.student_profile, name="student_profile")
]

tester/todo_list_10_user_profile/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    avatar = models.ImageField(
        default='avatar.jpg', # default avatar
        upload_to='profile_avatars' # dir to store the image
    )

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        # save the profile first
        super().save(*args, **kwargs)

        # resize the image
        img = Image.open(self.avatar.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            # create a thumbnail
            img.thumbnail(output_size)
            # overwrite the larger image
            img.save(self.avatar.path)
            
            
           

tester/todo_list_10_user_profile/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=254)
    
    class Meta:
        model = User
        fields = ('username',  'email', 'password1', 'password2', )
        

# for profile update
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']
        
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']        

tester/todo_list_10_user_profile/users/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login 
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render, redirect
from .forms import RegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views import View



class RegisterView(FormView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')
    
    def form_valid(self, form):
        user = form.save()
        if user:
            login(self.request, user)
            
        return super(RegisterView, self).form_valid(form)
    
    
class MyLoginView(LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True
    
    def get_success_url(self):
        return reverse_lazy('tasks') 
    
    def form_invalid(self, form):
        messages.error(self.request,'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))


class MyProfile(LoginRequiredMixin, View):
    def get(self, request):
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        
        return render(request, 'users/profile.html', context)
    
    def post(self,request):
        user_form = UserUpdateForm(
            request.POST, 
            instance=request.user
        )
        profile_form = ProfileUpdateForm(
            request.POST,
            request.FILES,
            instance=request.user.profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            
            messages.success(request,'Your profile has been updated successfully')
            
            return redirect('profile')
        else:
            context = {
                'user_form': user_form,
                'profile_form': profile_form
            }
            messages.error(request,'Error updating you profile')
            
            return render(request, 'users/profile.html', context)
            

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.urls import reverse
from .models import UserAppointment
from .forms import AdminRegistrationForm, StudentRegistrationForm, AdminProfileUpdateForm, StudentProfileUpdateForm, StudentAppointment1Form, StudentAppointment2Form, StudentAppointment4Form2

def admin_registration(request):
  if request.method == "POST":
    form = AdminRegistrationForm(request.POST, request.FILES)
    if form.is_valid():
      user = form.save()
      messages.success(request, "Admin Registration Successful! You Can Now Log In.")
      return redirect("users:user_login")
    else:
      messages.error(request, "Invalid Input! Please Try Again.")
      return redirect("users:admin_registration")
  else:
    form = AdminRegistrationForm()
  return render(request, "users/admin_registration.html", {"form": form})

def student_registration(request):
  if request.method == "POST":
    form = StudentRegistrationForm(request.POST, request.FILES)
    if form.is_valid():
      user = form.save()
      messages.success(request, "Student Registration Successful! You Can Now Log In.")
      return redirect("users:user_login")
    else:
      messages.error(request, "Invalid Input! Please Try Again.")
      return redirect("users:student_registration")
  else:
    form = StudentRegistrationForm()
  return render(request, "users/student_registration.html", {"form": form})

def user_login(request):
  if request.method == 'POST':
    username = request.POST.get('username')
    password = request.POST.get('password')
    role = request.POST.get('role')

    user = authenticate(request, username=username, password=password)

    if user is not None:
      if user.role == role:
        login(request, user)
        if user.role == 'admin':
          return redirect('users:admin_dashboard') 
        elif user.role == 'student':
          return redirect('users:student_home')
        else:
          messages.error(request, 'Invalid role selected for this user.')
          redirect("users:user_login")
      else:
        messages.error(request, 'Invalid username or password.')
        redirect("users:user_login")

  return render(request, 'users/login.html')

@login_required
def user_logout(request):
  logout(request)
  messages.success(request, "You have successfully logged out.")
  return redirect('index')

@login_required
def admin_dashboard(request):
  if not request.user.is_staff:
    messages.error(request, "You are not authorized to view this page.")
    raise PermissionDenied 

  return render(request, "users/admin/dashboard.html")

@login_required
def admin_inventory(request):
  if not request.user.is_staff:
    messages.error(request, "You are not authorized to view this page.")
    raise PermissionDenied
  return render(request, "users/admin/inventory.html")

@login_required
def admin_profile(request):
  if not request.user.is_staff:
    messages.error(request, "You are not authorized to view this page.")
    raise PermissionDenied

  if request.method == "POST":
    form = AdminProfileUpdateForm(request.POST, request.FILES, instance=request.user)
    if form.is_valid():
      form.save()
      messages.success(request, "Profile Successfully Updated.")
      return redirect("users:admin_profile")
    else:
      messages.error(request, "Profile could not be updated.")
  else:
    form = AdminProfileUpdateForm(instance=request.user)
  
  return render(request, "users/admin/profile.html", {"form": form})

@login_required
def admin_student_app(request):
  if not request.user.is_staff:
    messages.error(request, "You are not authorized to view this page.")
    raise PermissionDenied
  return render(request, "users/admin/student-app.html")

@login_required
def admin_student_history_profile(request):
  if not request.user.is_staff:
    messages.error(request, "You are not authorized to view this page.")
    raise PermissionDenied
  return render(request, "users/admin/student-history-sampleProfile.html")

@login_required
def admin_student_history(request):
  if not request.user.is_staff:
    messages.error(request, "You are not authorized to view this page.")
    raise PermissionDenied
  return render(request, "users/admin/student-history.html")

@login_required
def admin_student_record_profile(request):
  if not request.user.is_staff:
    messages.error(request, "You are not authorized to view this page.")
    raise PermissionDenied
  return render(request, "users/admin/student-record-sampleProfile.html")

@login_required
def admin_student_records(request):
  if not request.user.is_staff:
    messages.error(request, "You are not authorized to view this page.")
    raise PermissionDenied
  return render(request, "users/admin/student-records.html")

@login_required
def student_home(request):
  appointment = UserAppointment.objects.filter(user=request.user).last()
  return render(request, "users/student/home.html", {
    "appointment": appointment
  })

@login_required
def student_appointment1(request, appointment_id=None):
  if request.method == "POST":
    form = StudentAppointment1Form(request.POST)
    if form.is_valid():
      appointment = form.save(commit=False)
      appointment.user = request.user
      appointment.appointment_date = None
      appointment.appointment_time = None
      appointment.save()  
      messages.success(request, "Appointment 1 is Successful.")
      print(f"Redirecting to step 2 with appointment_id={appointment.id}")  
      return redirect("users:student_appointment2", appointment_id=appointment.id)
    else:
      print(form.errors)  
      messages.error(request, "Appointment 1 submission failed.")
  else:
    appointment = UserAppointment.objects.create(user=request.user)
    form = StudentAppointment1Form(instance=appointment)

  return render(request, "users/student/appointment-1.html", {
    "form": form,
    "appointment": appointment
  })

@login_required
def student_appointment2(request, appointment_id):
  appointment = get_object_or_404(UserAppointment, id=appointment_id)
  if request.method == "POST":
    form = StudentAppointment2Form(request.POST, instance=appointment)
    if form.is_valid():
      appointment = form.save(commit=False)
      appointment.user = request.user
      appointment.save()
      messages.success(request, "Appointment 2 is Successful.")
      print(f"Redirecting to step 3 with appointment_id={appointment.id}")  
      return redirect("users:student_appointment3", appointment_id=appointment.id)
    else:
      messages.error(request, "Appointment 2 submission failed.")
  else:
    form = StudentAppointment2Form(instance=appointment)

  return render(request, "users/student/appointment-2.html", {
    "form": form,
    "appointment": appointment
  })

@login_required
def student_appointment3(request, appointment_id):
  appointment = get_object_or_404(UserAppointment, id=appointment_id)
  return render(request, "users/student/appointment-3.html", {"appointment": appointment})

@login_required
def student_appointment4_form2(request, appointment_id):
  appointment = get_object_or_404(UserAppointment, id=appointment_id)
  if request.method=="POST":
    form = StudentAppointment4Form2(request.POST, request.FILES, instance=appointment)
    if form.is_valid():
      appointment = form.save(commit=False)
      appointment.user = request.user
      appointment.save()
      messages.success(request, "Appointment 4 is Successful.")
      print(f"Redirecting to step 5 with URL: {reverse('users:student_appointment5', kwargs={'appointment_id': appointment.id})}")
      print(f"Redirecting to step 5 with appointment_id={appointment.id}")
      return redirect("users:student_appointment5", appointment_id=appointment.id)
    else:
      print(form.errors)
      messages.error(request, "Appointment 4 submission failed.")
  else:
    form = StudentAppointment4Form2(instance=appointment)

  return render(request, "users/student/appointment-4-form2.html", {
    "form": form,
    "appointment": appointment
  })

@login_required
def student_appointment5(request, appointment_id):
  appointment = get_object_or_404(UserAppointment, id=appointment_id)
  return render(request, "users/student/appointment-5.html", {"appointment": appointment})

@login_required
def student_profile(request):
  if request.method == "POST":
    form = StudentProfileUpdateForm(request.POST, request.FILES, instance=request.user)
    if form.is_valid():
      form.save()
      messages.success(request, "Profile Successfully Updated.")
      return redirect("users:student_profile")
    else:
      messages.error(request, "Profile could not be updated.")
  else:
    form = StudentProfileUpdateForm(instance=request.user)

  return render(request, "users/student/profile.html", {"form": form})

users/templates/layout/admin_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock title %}
  </title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  <link rel="stylesheet" href="{% static 'admin/assets/css/header.css' %}">
  <link rel="stylesheet" href="{% static 'admin/assets/css/sidebar.css' %}">
  <link rel="stylesheet" href="{% static 'admin/assets/css/dashboard.css' %}">
  <link rel="stylesheet" href="{% static 'admin/assets/css/profile.css' %}">
  <link rel="stylesheet" href="{% static 'admin/assets/css/student-app.css' %}">
  <link rel="stylesheet" href="{% static 'admin/assets/css/student-history.css' %}">
  <link rel="stylesheet" href="{% static 'admin/assets/css/student-history-sampleProfile.css' %}">
  <link rel="stylesheet" href="{% static 'admin/assets/css/student-record.css' %}">
  <link rel="stylesheet" href="{% static 'admin/assets/css/student-record-sampleProfile.css' %}">
  
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

  <script src="{% static 'admin/assets/js/dashboard.js' %}" defer></script>
  <script src="{% static 'admin/assets/js/header.js' %}" defer></script>
  <script src="{% static 'admin/assets/js/sidebar.js' %}" defer></script>
  <script src="{% static 'admin/assets/js/chart.js' %}" defer></script>

  {% block css %}
  {% endblock css %}

  {% block style %}
  {% endblock style %}
</head>

{% block header %}
{% endblock header %}

<body>
  
  <!-- Main Container -->
  <main>
    <nav class="header">
      <div class="header-left">
        <a href="{% url 'users:admin_dashboard' %}" class="logo">
          <img src="{% static 'admin/assets/img/logo.png' %}" width="90" height="80" alt="" class="mx-2 my-1">
        </a>
        <div class="header-title">
          <h2 class="h2 mb-0">Health Services Office</h2>
        </div>
      </div>

      <div class="header-right">
        <a href="#">
          <i class="fas fa-user"></i>
          <span class="account-name">Account Name</span>
        </a>
        <i class="fas fa-chevron-down"></i>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item profile" href="{% url 'users:admin_profile' %}">Profile</a></li>
          <li><a class="dropdown-item logout" href="{% url 'users:user_logout' %}">Log Out</a></li>
        </ul>
      </div>
    </nav>

    <div class="pink-line"></div>

    <!-- Main Content Area -->
    <div class="main-container">
      <div class="sidebar">
        <div class="sidebar-title">Menu</div>
        <ul class="sidebar-menu">
          <li><a href="{% url 'users:admin_dashboard' %}" class="active"><i class="fas fa-tachometer-alt icon"></i>Dashboard</a></li>
          <li><a href="{% url 'users:admin_profile' %}"><i class="fas fa-user icon"></i>Profile</a></li>
          <li><a href="{% url 'users:admin_student_app' %}"><i class="fas fa-users icon"></i>Students</a></li>
          <li><a href="{% url 'users:admin_inventory' %}"><i class="fas fa-box icon"></i>Inventory</a></li>
        </ul>
      </div>
      {% block content %}
      {% endblock content %}
    </div>
  </main>

  {% block section %}
  {% endblock section %}
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-ZR0piH4RZr8ivC7k8Zkx1EMbO0lzwi1E4hZ6I6bg9HiU2nTx1WI3KNQ/wzZ9aOPz" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/2hb6i8Jit6N4sUW5mhw5z8X50Ff5Z0X3FIFUJc" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4/Jqs6hgt+f5Njo+Xlb8BL6NxKODu7bBJ+VJjqM1VW1T9OBI1WZ2kcst7" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-QLNWaw6BnPcFGH4PYN8h6GP+15GS0FL6DdN1FKhPbDCRu3rNhUEY0m9a7xm4Y7RA" crossorigin="anonymous"></script>

  <script src="{% static '/admin/assets/js/student-app.js' %}" defer></script>
  <script src="{% static '/admin/assets/js/student-history.js' %}" defer></script>
  <script src="{% static '/admin/assets/js/student-history-sampleProfile.js' %}" defer></script>
  <script src="{% static '/admin/assets/js/student-record-sampleProfile.js' %}" defer></script>

  {% block js %}
  {% endblock js %}  
</body>

{% block footer %}
{% endblock footer %}

</html>

users/templates/layout/student_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  
  <link rel="stylesheet" href="{% static 'student/assets/css/header.css' %}">
  <link rel="stylesheet" href="{% static 'student/assets/css/home.css' %}">
  <link rel="stylesheet" href="{% static 'student/assets/css/profile.css' %}">
  <link rel="stylesheet" href="{% static 'student/assets/css/appointment-1.css' %}">
  <link rel="stylesheet" href="{% static 'student/assets/css/appointment-2.css' %}">
  <link rel="stylesheet" href="{% static 'student/assets/css/appointment-3.css' %}">
  <link rel="stylesheet" href="{% static 'student/assets/css/appointment-4-form1.css' %}">
  <link rel="stylesheet" href="{% static 'student/assets/css/appointment-4-form2.css' %}">
  <link rel="stylesheet" href="{% static 'student/assets/css/appointment-5.css' %}">

  {% block css %}
  {% endblock css %}

  {% block style %}
  {% endblock style %}
</head>

{% block header %}
{% endblock header %}

<body>
  {% block navbar %}
  {% endblock navbar %}
  
  <!-- Main Container -->
  <main>
    <!-- Header -->
    <div class="header">
      <div class="header-left">
        <a href="{% url 'users:student_home' %}" class="logo">
          <img src="{% static 'student/assets/img/logo.png' %}" width="90" height="80" alt="" class="mx-2 my-1">
        </a>
        <div class="header-title">
          <h2 class="h2 mb-0">Health Services Office</h2>
        </div>
      </div>
      <div class="header-right">
        <a href="{% url 'users:student_home' %}" class="active">Home</a>
        <a href="schedule.html">My Schedule</a>
        <a href="request.html">Request</a>
        <div class="dropdown">
          <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Profile<i class="fas fa-circle-user"></i>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'users:student_profile' %}">View Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'users:user_logout' %}">Log Out</a></li>
          </ul>
        </div>
      </div>
      <div class="pink-line"></div>
    </div>
    <!-- End Header -->

    <!-- Main Content Area -->
    <div class="main-container">
      <!-- Content Area -->
      {% block content %}
      {% endblock content %}
    </div>
    <!-- End Main Content Area -->
  </main>
  <!-- End Main Container -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>

  <script src="{% static '/student/assets/js/appointment-1.js' %}" defer></script>
  <script src="{% static '/student/assets/js/appointment-2.js' %}" defer></script>
  <script src="{% static '/student/assets/js/appointment-3.js' %}" defer></script>
  <script src="{% static '/student/assets/js/appointment-4.js' %}" defer></script>
  <script src="{% static '/student/assets/js/appointment-5.js' %}" defer></script>

  {% block js %}
  {% endblock js %}  
</body>

</html>