healthclinic_system/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("", views.index, name="index"),
    path("users/", include("users.urls", namespace="users"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tester/todo_list_1/todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls'))
]

tester/todo_list_10_user_profile/todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls')),
    path('',include('users.urls'))
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = "users"

urlpatterns = [
  path("admin/", admin.site.urls),

  path("register/admin", views.admin_registration, name="admin_registration"),
  path("register/student", views.student_registration, name="student_registration"),

  path("bsu-alangilan/login", views.user_login, name="user_login"),
  path("bsu-alangilan/logout", views.user_logout, name="user_logout"),

  path("user-admin/dashboard", views.admin_dashboard, name="admin_dashboard"),
  path("user-admin/inventory", views.admin_inventory, name="admin_inventory"),
  path("user-admin/profile", views.admin_profile, name="admin_profile"),
  path("user-admin/student_app", views.admin_student_app, name="admin_student_app"),
  path("user-admin/student_history_profile", views.admin_student_history_profile, name="admin_student_history_profile"),
  path("user-admin/student_history", views.admin_student_history, name="admin_student_history"),
  path("user-admin/student_record_profile", views.admin_student_record_profile, name="admin_student_record_profile"),
  path("user-admin/student_records", views.admin_student_records, name="admin_student_records"),

  path("user-student/home", views.student_home, name="student_home"),
  path("user-student/appointment1", views.student_appointment1, name="student_appointment1"),
  path("user-student/appointment1/<int:appointment_id>", views.student_appointment1, name="student_appointment1_with_id"),
  path("user-student/appointment2/<int:appointment_id>", views.student_appointment2, name="student_appointment2"),
  path("user-student/appointment3/<int:appointment_id>", views.student_appointment3, name="student_appointment3"),
  path("user-student/appointment4_form2/<int:appointment_id>", views.student_appointment4_form2, name="student_appointment4_form2"),
  path("user-student/appointment5/<int:appointment_id>", views.student_appointment5, name="student_appointment5"),
  path("user-student/profile", views.student_profile, name="student_profile")
]

templates/index.html
{% extends "main_layout.html" %}
{% load static %}

{% block title %}
  Health Services Office - BSU Alangilan Campus
{% endblock title %}

{% block css %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link rel="stylesheet" href="{% static 'assets/css/homepage.css' %}">
{% endblock css %}

{% block navbar %}
  <nav class="header d-flex justify-content-between align-items-center p-3 bg-white shadow-sm">
    <div class="header-left">
      <a href="/" class="logo">
        <img src="{% static 'assets/img/logo.png' %}" width="90" height="80" alt="BatStateU Logo" class="mx-2 my-1">
      </a>
    </div>
    <div class="contact-info">
      <p>Local number: 2140</p>
      <p>Email: healthservices.alangilan@g.batstate-u.edu.ph</p>
    </div>
  </nav>
{% endblock navbar %}

{% block content %}
  <main>
    <div class="main-container">
      <div class="left-panel">
        <div class="contents">
          <h1>This is BatStateU Alangilan</h1>
          <h2>HEALTH SERVICES OFFICE</h2>
          <div class="buttons">
            <a href="#" id="registerBtn">Register</a>
            <a href="{% url 'users:user_login' %}">Login</a>
          </div>
        </div>
      </div>
      <div class="right-panel">
        <div class="overlay"></div>
      </div>
    </div>
  </main>

  <div id="myModal" class="modal">
    <div class="modal-content">
     
      <div class="modal-body">
        <span class="modal-close">&times;</span>
        <h6>Register As</h6>
        <div class="button-container">
          <a href="{% url 'users:admin_registration' %}" class="admin-link">Admin</a>
          <a href="{% url 'users:student_registration' %}" class="student-link">Student</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static 'assets/js/homepageModal.js' %}" defer></script>
{% endblock js %}

templates/main_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock title %}
  </title>

  {% block css %}
  {% endblock css %}  
</head>

{% block header %}
{% endblock header %}

<body>
  {% block navbar %}
  {% endblock navbar %}

  {% block content %}
  {% endblock content %}
  
  {% block js %}
  {% endblock js %}  
</body>

{% block footer %}
{% endblock footer %}

</html>